services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    container_name: nginx
    build: ./ScheduleBuilder
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.nginx.rule=Host(`claretformun.com`) || Host(`www.claretformun.com`)
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls=true

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: claret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data

  api:
    container_name: api
    restart: always
    build: ./API
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "postgresql://postgres:admin@postgres:5432/claret"
      REDIS_URL: "redis:6379"
      SCRAPER_ENABLED: "true"
      SCRAPER_ALL: "true"
      SCRAPER_WEBHOOK_URL: ${WEBHOOK_URL}
      API_ENABLED: "true"
      GIN_MODE: "release"
      API_RATE_LIMIT_ENABLED: "true"
      API_RATE_LIMIT: "120-M"
      PORT: 8080
      TZ: America/St_Johns
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.http.routers.api.rule=Host(`api.claretformun.com`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
