version: "3"

networks:
  network:
    ipam:
      config:
        - subnet: 172.12.0.0/24

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    networks:
      network:
        ipv4_address: 172.12.0.2
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - --certificatesresolvers.letsencrypt.acme.email=evanw
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: WebServer.Dockerfile
    networks:
      network:
        ipv4_address: 172.12.0.3
    environment:
      - API_URL=https://api.evaan.dev
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.nginx.rule=Host(`claretformun.com`)
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls=true

  postgres:
    image: postgres
    restart: always
    networks:
      network:
        ipv4_address: 172.12.0.4
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: claret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  claretapi:
    container_name: claretAPI
    restart: always
    build:
      context: .
      dockerfile: API.Dockerfile
    networks:
      network:
        ipv4_address: 172.12.0.5
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgresql://postgres:admin@172.12.0.4:5432/claret"
      PORT: 8080
      TZ: America/St_Johns
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.http.routers.api.rule=Host(`api.claretformun.com`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true

  claretscraper:
    container_name: claretScraper
    #restart: always
    build:
      context: .
      dockerfile: Scraper.Dockerfile
    networks:
      network:
        ipv4_address: 172.12.0.6
    depends_on:
      - postgres
    environment:
      DB_URL: "postgresql://postgres:admin@172.12.0.4:5432/claret"
      PORT: 8080
      TZ: America/St_Johns

  icsserver:
    container_name: icsServer
    #restart: always
    build:
      context: .
      dockerfile: ICSServer.Dockerfile
    networks:
      network:
        ipv4_address: 172.12.0.7
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_URL: "postgresql://postgres:admin@172.12.0.4:5432/claret"
      PORT: 8000
      TZ: America/St_Johns
      BANNER_TZ: America/St_Johns
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.http.routers.ics.rule=Host(`claret-ics.evaan.dev`)
      - traefik.http.routers.ics.entrypoints=websecure
      - traefik.http.routers.ics.tls=true