name: Deploy to GitHub Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata for Docker (Server)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: evaan/claret-server

      - name: Build and push Docker image (Server)
        uses: docker/build-push-action@v3
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}