# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ScheduleBuilder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ScheduleBuilder/

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        path: client
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - run: npm install

    - run: npm build
